# Generated by Django 4.2.1 on 2024-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convertor", "0003_convertedfile_pdffile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convertedfile",
            name="csv_file",
            field=models.FileField(upload_to="receipts/converted_csv/"),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="file",
            field=models.FileField(upload_to="receipts/"),
        ),
    ]
